"""empty message

Revision ID: 865717615f48
Revises: 0d249c5cafcb
Create Date: 2024-03-12 17:28:26.709825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865717615f48'
down_revision = '0d249c5cafcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('detail_firstImgUrl', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('detail_firstImgUrl')
        batch_op.drop_column('detail_text')

    # ### end Alembic commands ###
